# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/sources_1/new/clockdiv.sv
  D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/sources_1/new/segdisplay.sv
  D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/sources_1/new/keyboard.sv
  D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/sources_1/new/vga640x480.sv
  D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/sources_1/new/NERP_demo_top.sv
}
read_xdc D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS.001/Desktop/NERP/slak.srcs/constrs_1/new/cons.xdc]

synth_design -top TopModule -part xc7a35tcpg236-1
write_checkpoint -noxdef TopModule.dcp
catch { report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb }
